# Makefile.dep created Sun Nov 22 09:13:56 PST 2020
debug.o: debug.cpp debug.h util.h util.tcc
util.o: util.cpp debug.h util.h util.tcc
main.o: main.cpp listmap.h debug.h xless.h xpair.h listmap.tcc util.h \
 util.tcc
